version: "3.7"

services:
  database_ignite:
  image: postgres
  container_name: database_ignite
  restart: always
  ports: -5432:5432
  enviroment:
    - POSTGRES_USER=docker
    - POSTGREES_PASSWORD=ignite
    - POSTGREES_DB=rentx
  volumes:
    - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app


volumes:
  pgdata:
    driver: local
